%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Abbas\Documents\CIG\outputMat0.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/02/15 14:22:51

for i=0:9
    %% Initialize variables.en
    filename = strcat('C:\Users\Abbas\Documents\comp-intelligence\outputMat',num2str(i),'.txt');
    delimiter = '\t';
    startRow = 2;

    %% Format string for each line of text:
    %   column1: double (%f)
    %	column2: double (%f)
    %   column3: double (%f)
    % For more information, see the TEXTSCAN documentation.
    formatSpec = '%f%f%f%[^\n\r]';

    %% Open the text file.
    fileID = fopen(filename,'r');

    %% Read columns of data according to format string.
    % This call is based on the structure of the file used to generate this
    % code. If an error occurs for a different file, try regenerating the code
    % from the Import Tool.
    dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

    %% Close the text file.
    fclose(fileID);

    %% Post processing for unimportable data.
    % No unimportable data rules were applied during the import, so no post
    % processing code is included. To generate code which works for
    % unimportable data, select unimportable cells in a file and regenerate the
    % script.

    %% Allocate imported array to column variable names
    Gen = dataArray{:, 1};
    avgX = dataArray{:, 2};
    bestX = dataArray{:, 3};
    optimal = zeros(200,1);
    for j=1:200
        optimal(j) = .7572;
    end
    
    figure; title(strcat('Run',num2str(i)));
    hold on;
    plot(dataArray{:,1}, dataArray{:,2});
    plot(dataArray{:,1}, dataArray{:,3});
    plot(dataArray{:,1}, optimal, 'g');
    % for i=0:200
    %     plot(dataArray{i,1}, dataArray{i,2});
    %     plot(dataArray{i,1}, dataArray{i,3});
    % end

    %% Clear temporary variables
    clearvars filename delimiter startRow formatSpec fileID dataArray ans;
end
    
